### ISSUE TITLE
Bug or Feature?

### ISSUE THREAD

**Issue by Zhiwen-Xiao** [WunschUnreif/CS383-Visualization#1]
Expressions like 6/02 seems not available. Type error!

**Comment by WunschUnreif** [comment]
This was a mistake of the CFG.
Originally it was recognized as ((6 / 0) (2)) which passed the parsing but failed the type checking.
Now I've changed the grammar so this will be regarded as syntax error.
By now octal representations are not supported, so numbers like `02` is not allowed.
